blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'', include('blogs.urls', namespace='blogs')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
]

blogs/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # topic
    url(r'^topics$', views.topics, name='topics'),
    url(r'^new_topic$', views.new_topic, name='new_topic'),
    url(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name='delete_topic'),

    # tag
    url(r'^tags$', views.tags, name='tags'),
    url(r'^new_tag$', views.new_tag, name='new_tag'),
    url(r'^delete_tag/(?P<tag_id>\d+)/$', views.delete_tag, name='delete_tag'),

    # post
    url(r'^post/(?P<post_id>\d+)/$', views.post, name='post'),
    url(r'^posts/(?P<username>\w+)/$', views.posts_user, name='posts_user'),
    url(r'^posts/topic/(?P<topic_id>\d+)/$', views.posts_topic, name='posts_topic'),
    url(r'^posts/tag/(?P<tag_id>\d+)/$', views.posts_tag, name='posts_tag'),
    url(r'^posts/manager$', views.posts_manger, name='posts_manager'),
    url(r'^new_post$', views.new_post, name='new_post'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogs/models.py
from django.db import models
# from django.contrib.auth.models import User
from users.models import User


class Topic(models.Model):
    """博客主题"""
    text = models.CharField(max_length=20, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text


class Tag(models.Model):
    """文章标签"""
    text = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.text


class Post(models.Model):
    """博客文章"""
    title = models.CharField(max_length=200)
    summary = models.TextField()
    # tags = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag, verbose_name="标签", blank=True)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    # 封面图，后面改为上传图片
    cover = models.TextField()
    topic = models.ForeignKey(Topic)
    read_count = models.IntegerField()  # 阅读量

    def __str__(self):
        return self.title

blogs/forms.py
from django import forms

from .models import Topic, Post

cols_ = {'cols': 80}


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': '主题'}
        widgets = {'text': forms.TextInput(attrs=cols_)}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['topic', 'title', 'cover', 'summary', 'text', 'tags']
        labels = {'topic': '主题/分类', 'title': '标题', 'summary': '摘要', 'tags': '标签', 'text': '文本', 'cover': '封面图'}
        widgets = {'topic': forms.Select(attrs=cols_),
                   'title': forms.TextInput(attrs=cols_),
                   'summary': forms.Textarea(attrs=cols_),
                   'tags': forms.TextInput(attrs=cols_),
                   'text': forms.Textarea(attrs=cols_),
                   'cover': forms.TextInput()}

blogs/views.py
from django.shortcuts import render
from users.models import User
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Post, Topic, Tag
from .forms import PostForm


def index(request):
    """系统主页"""
    posts = Post.objects.order_by('-date_added')
    context = {'posts': posts}

    return render(request, 'blogs/index.html', context)


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('-date_added')
    context = {'topics': topics}
    return render(request, 'blogs/topics.html', context)


@login_required
def new_topic(request):
    """添加新主题"""
    if request.method == 'POST':
        topic = Topic()
        topic.text = request.POST['topic']
        topic.owner = request.user
        topic.save()

        return HttpResponseRedirect(reverse('blogs:topics'))

    return render(request, 'blogs/new_topic.html')


@login_required
def delete_topic(request, topic_id):
    """删除主题"""
    topic = Topic.objects.filter(owner=request.user).get(id=topic_id)
    if topic:
        topic.delete()
        return topics(request)
    else:
        raise Http404


@login_required
def tags(request):
    """标签列表"""
    tags = Tag.objects.filter(owner=request.user).order_by('-date_added')
    context = {'tags': tags}
    return render(request, 'blogs/tags.html', context)


@login_required
def new_tag(request):
    """新增标签"""
    if request.method == 'POST':
        tag = Tag()
        tag.text = request.POST['tag']
        tag.owner = request.user
        tag.save()

        return HttpResponseRedirect(reverse('blogs:tags'))

    return render(request, 'blogs/new_tag.html')


@login_required
def delete_tag(request, tag_id):
    """删除标签"""
    tag = Tag.objects.filter(owner=request.user).get(id=tag_id)
    if tag:
        tag.delete()
        return HttpResponseRedirect(reverse('blogs:tags'))
    else:
        raise Http404


def post(request, post_id):
    """文章页"""
    post = Post.objects.get(id=post_id)
    if post:
        context = {'post': post}
        post.read_count += 1
        post.save()
        return render(request, 'blogs/post.html', context)
    else:
        raise Http404


def posts_topic(request, topic_id):
    """文章列表"""
    posts = []
    if topic_id:
        topic = Topic.objects.get(id=topic_id)
        posts = Post.objects.filter(topic=topic).order_by('-date_added')

    context = {'posts': posts}
    return render(request, 'blogs/post_user.html', context)


def posts_tag(request, tag_id):
    """文章列表"""
    posts = []
    if tag_id:
        tag = Tag.objects.get(id=tag_id)
        posts = Post.objects.filter(tags=tag).order_by('-date_added')

    context = {'posts': posts}
    return render(request, 'blogs/post_user.html', context)


def posts_user(request, username):
    """用户主页"""
    if username:
        target = User.objects.get(username=username)
        if not target:
            raise Http404
    else:
        if request.user.is_authenticated():
            target = request.user
        else:
            raise Http404

    topics = Topic.objects.filter(owner=target).order_by('-date_added')
    posts = Post.objects.filter(owner=target).order_by('-date_added')
    context = {'topics': topics, 'posts': posts, 'target': target}
    return render(request, 'blogs/post_user.html', context)


@login_required
def posts_manger(request):
    """文章管理"""
    posts = Post.objects.filter(owner=request.user).order_by('-date_added')

    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)


@login_required
def new_post(request):
    """发布新文章"""
    if request.method == 'POST':
        # form = PostForm(request.POST)
        # new_post = form.save()
        data = request.POST
        title = data['title']
        summary = data['summary']
        tags = data['tags']
        text = data['text']
        cover = data['cover']
        topic = Topic.objects.filter(owner=request.user).get(id=data['topic'])

        new_post = Post()
        new_post.title = title
        new_post.summary = summary
        new_post.tags = tags
        new_post.text = text
        new_post.owner = request.user
        new_post.cover = cover
        new_post.topic = topic
        new_post.save()

        return HttpResponseRedirect(reverse('blogs:post', args=[new_post.id]))
    else:
        form = PostForm()

    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def delete_post(request, post_id):
    """删除文章"""
    post = Post.objects.filter(owner=request.user).get(id=post_id)
    if post:
        post.delete()
        return posts_manger(request)
    else:
        raise Http404


@login_required
def edit_post(request, post_id):
    """编辑文章"""
    if request.method != 'POST':
        post = Post.objects.filter(owner=request.user).get(id=post_id)
        context = {'post': post}
        return render(request, 'blogs/edit_post.html', context)
    else:
        data = request.POST
        title = data['title']
        summary = data['summary']
        tags = data['tags']
        text = data['text']
        cover = data['cover']
        topic = data['topic']

        new_post = Post()
        new_post.id = post_id
        new_post.title = title
        new_post.summary = summary
        new_post.tags = tags
        new_post.text = text
        new_post.owner = request.user
        new_post.cover = cover
        new_post.topic = topic
        new_post.save()

        return HttpResponseRedirect(reverse('blogs:post', args=[new_post.id]))

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}


{% block menu %}
    <li class="nav-current" role="presentation"><a href="/">首页</a></li>
    <li role="presentation"><a href="https://github.com/duozhilin/Blog" target="_blank">fork me</a></li>
    <li role="presentation"><a href="/ghost-cheat-sheet/">快捷手册</a></li>
    <li role="presentation"><a href="http://docs.ghostchina.com/zh/">中文文档</a></li>
    <li role="presentation"><a href="/download/">下载</a></li>
    <li role="presentation"><a href="/about/">关于</a></li>
{% endblock menu %}

{% block main %}
	<main class="col-md-8 main-content">
		{% include "blogs/post_list.html" %}
	</main>
{% endblock main %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block container %}


<h1>添加文章</h1>

<form action="{% url 'blogs:new_post' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button type="submit" class="btn btn-default">保存</button>
    {% endbuttons %}
</form>


{% endblock container %}

blogs/templates/blogs/new_tag.html
{% extends "blogs/base.html" %}


{% block container %}

    <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-xs-10 col-sm-8 col-md-6">
        <form class="form-horizontal" method="post" action="{% url 'blogs:new_tag' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_tag" class="col-sm-3 col-sm-3 control-label">标签 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="tag" id="id_tag" class="form-control" placeholder="标签" maxlength="20" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-4">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock container %}

blogs/templates/blogs/new_topic.html
{% extends "blogs/base.html" %}


{% block container %}

    <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-xs-10 col-sm-8 col-md-6">
        <form class="form-horizontal" method="post" action="{% url 'blogs:new_topic' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_topic" class="col-sm-3 col-sm-3 control-label">主题 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="topic" id="id_topic" class="form-control" placeholder="主题" maxlength="20" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-4">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock container %}

blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}


{% block main %}
	<main class="col-md-8 main-content">	                
		<article id="108" class="post">

		    <header class="post-head">
		        <h1 class="post-title">{{ post.title }}</h1>
		        <section class="post-meta">
		            <span class="author">作者：<a href="{% url 'blogs:posts_user' post.owner.username %}">{{ post.owner.nickname }}</a></span> &bull;
		            <time class="post-date" datetime="{{ post.date_added|date:'Y年m月d日 H:i' }}" title="{{ post.date_added|date:'Y年m月d日 H:i' }}">{{ post.date_added|date:'Y年m月d日 H:i' }}</time>
		        </section>
		    </header>
		    <section class="featured-media">
		        <img src="{{ post.cover }}" alt="{{ post.title }}">
		    </section>

		    <section class="post-content">
		        {{ post.text|safe }}
		    </section>

		    <footer class="post-footer clearfix">
		        <div class="pull-left tag-list">
		            <i class="fa fa-folder-open-o"></i>
		            
		        </div>

		        <div class="pull-right share">
		            <div class="bdsharebuttonbox share-icons">
					    <a href="#" class="bds_more" data-cmd="more"></a>
					    <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
					    <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
					    <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
					    <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
					    <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
					</div>        
				</div>
		    </footer>

		</article>

		<div class="about-author clearfix">
		    <a href="/author/wangsai/"><img src="{{ post.owner.avatar }}" alt="{{ post.owner.nickname }}" class="avatar pull-left"></a>
		    
		    <div class="details">
		        <div class="author">
		            关于作者 <a href="{% url 'blogs:posts_user' post.owner.username %}">{{ post.owner.nickname }}</a>
		        </div>
		        <div class="meta-info">
		            <span class="loaction"><i class="fa fa-home"></i>{{ post.owner.city }}</span>
		            <span class="website"><i class="fa fa-globe"></i><a href="{{ post.owner.site }}" targer="_blank">个人网站/博客</a></span>
		        </div>
		    </div>
		</div>

		<div class="prev-next-wrap clearfix">
		    <a class="btn btn-default" href="/primary-tags/"><i class="fa fa-angle-left fa-fw"></i> 首要“标签”</a>
		    &nbsp;
		</div>
    </main>

{% endblock main %}

blogs/templates/blogs/post_list.html
{% for post in posts %}
    <article id={{ post.id }} class="post tag-release tag-about-ghost">

        <div class="post-head">
            <h1 class="post-title"><a href="{% url 'blogs:post' post.id %}">{{ post.title }}</a></h1>
            <div class="post-meta">
                <span class="author">作者：<a href="{% url 'blogs:posts_user' post.owner.username %}">{{ post.owner.nickname }}</a></span> &bull;
                <time class="post-date" datetime="{{ post.date_added|date:'Y年m月d日 H:i' }}" title="{{ post.date_added|date:'Y年m月d日 H:i' }}">{{ post.date_added|date:'Y年m月d日 H:i' }}</time>
            </div>
        </div>
        <div class="featured-media">
            <a href="{% url 'blogs:post' post.id %}"><img src="{{ post.cover }}" alt="{{ post.title }}"></a>
        </div>
        <div class="post-content">
            <p>{{ post.summary }}</p>
        </div>
        <div class="post-permalink">
            <a href="{% url 'blogs:post' post.id %}" class="btn btn-default">阅读全文</a>
        </div>

        <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
                <i class="fa fa-tags"></i>
                <a href="/tag/release/">{{ post.keywords }}</a>, <a href="/tag/about-ghost/">Ghost</a>
            </div>
            <div class="pull-right share">
            </div>
        </footer>
    </article>
{% empty %}
	你还没有发布过文章
{% endfor %}

<nav class="pagination" role="navigation">
    <span class="page-number">第 1 页 &frasl; 共 9 页</span>
        <a class="older-posts" href="/page/2/"><i class="fa fa-angle-right"></i></a>
</nav>

blogs/templates/blogs/post_manager.html
{% for post in posts %}
    <article id={{ post.id }} class="post tag-release tag-about-ghost">

        <div class="post-head">
            <h1 class="post-title"><a href="{% url 'blogs:post' post.id %}">{{ post.title }}</a></h1>
            <div class="post-meta">
                <span class="author">作者：<a href="{% url 'blogs:posts_user' post.owner.username %}">{{ post.owner.nickname }}</a></span> &bull;
                <time class="post-date" datetime="{{ post.date_added|date:'Y年m月d日 H:i' }}" title="{{ post.date_added|date:'Y年m月d日 H:i' }}">{{ post.date_added|date:'Y年m月d日 H:i' }}</time>
            </div>
        </div>
        <div class="featured-media">
            <a href="{% url 'blogs:post' post.id %}"><img src="{{ post.cover }}" alt="{{ post.title }}"></a>
        </div>
        <div class="post-content">
            <p>{{ post.summary }}</p>
        </div>
        <div class="post-permalink">
            <a href="{% url 'blogs:post' post.id %}" class="btn btn-default">阅读全文</a>
        </div>

        <footer class="post-footer clearfix">
            <div class="pull-left tag-list">
                <i class="fa fa-tags"></i>
                <a href="/tag/release/">{{ post.keywords }}</a>, <a href="/tag/about-ghost/">Ghost</a>
            </div>
            <div class="pull-right share">
            </div>
        </footer>
    </article>
{% empty %}
	你还没有发布过文章
{% endfor %}

<nav class="pagination" role="navigation">
    <span class="page-number">第 1 页 &frasl; 共 9 页</span>
        <a class="older-posts" href="/page/2/"><i class="fa fa-angle-right"></i></a>
</nav>

blogs/templates/blogs/post_user.html
{% extends 'blogs/base.html' %}


{% block main %}
	<main class="col-md-8 main-content">
        {% if target %}
            <div class="cover author-cover">
                <div class="avatar-wrap">
                    <img src="{{ target.avatar }}" alt="{{ target.nickname }}" class="avatar">
                </div>
                <h3 class="author-name">
                    作者：{{target.nickname}}
                </h3>
                <div class="meta-info">
                    <span class="post-count"><i class="fa fa-pencil-square-o"></i>{{ target.post_set.all|length }}篇文章</span>
                    <span class="loaction"><i class="fa fa-map-marker"></i>{{ target.city }}</span>
                    <span class="website"><i class="fa fa-globe"></i><a href="{{target.site }}" targer="_BLANK">个人网站/博客</a></span>
                </div>
                <div class="bio"></div>
            </div>
        {% endif %}
		
		{% include "blogs/post_list.html" %}
	</main>

{% endblock main %}

blogs/templates/blogs/posts.html
{% extends 'blogs/base.html' %}


{% block container %}
    <div>
        <a href="{% url 'blogs:new_post' %}" class="btn btn-default" role="button">新增</a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr><th>id</th><th>主题/分类</th><th>添加时间</th><th>添加人</th><th>标题</th><th>阅读量</th><th>操作</th></tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td><a href="{% url 'blogs:posts_topic' post.topic.id %}"> {{ post.topic }}</a></td>
                    <td>{{ post.date_added|date:'Y年m月d日 H:i' }}</td>
                    <td>{{ post.owner.nickname }}</td>
                    <td><a href="{% url 'blogs:post' post.id %}"> {{ post }} </a></td>
                    <td>{{ post.read_count }}</td>
                    <td><a href="{% url 'blogs:delete_post' post.id %}"><i class="fa fa-remove"></i></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock container %}

blogs/templates/blogs/tags.html
{% extends 'blogs/base.html' %}


{% block container %}
    <div>
        <a href="{% url 'blogs:new_tag' %}" class="btn btn-default" role="button">新增</a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr><th>id</th><th>标签</th><th>添加时间</th><th>添加人</th><th>文章数量</th><th>操作</th></tr>
            {% for tag in tags %}
                <tr>
                    <td>{{ tag.id }}</td>
                    <td><a href="{% url 'blogs:posts_tag' tag.id %}"> {{ tag }}</a></td>
                    <td>{{ tag.date_added|date:'Y年m月d日 H:i' }}</td>
                    <td>{{ tag.owner.nickname }}</td>
                    <td>{{ tag.post_set.all|length }}</td>
                    <td><a href="{% url 'blogs:delete_tag' tag.id %}"><i class="fa fa-remove"></i></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock container %}

blogs/templates/blogs/topics.html
{% extends 'blogs/base.html' %}


{% block container %}
    <div>
        <a href="{% url 'blogs:new_topic' %}" class="btn btn-default" role="button">新增</a>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <tr><th>id</th><th>主题/分类</th><th>添加时间</th><th>添加人</th><th>文章数量</th><th>操作</th></tr>
            {% for topic in topics %}
                <tr>
                    <td>{{ topic.id }}</td>
                    <td><a href="{% url 'blogs:posts_topic' topic.id %}"> {{ topic }}</a></td>
                    <td>{{ topic.date_added|date:'Y年m月d日 H:i' }}</td>
                    <td>{{ topic.owner.nickname }}</td>
                    <td>{{ topic.post_set.all|length }}</td>
                    <td><a href="{% url 'blogs:delete_topic' topic.id %}"><i class="fa fa-remove"></i></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock container %}