blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'', include('blogs.urls', namespace='blogs')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.conf import settings
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^login$', views.login_view, name='login_view'),
    url(r'^logout$', views.logout_view, name='logout_view'),
    url(r'^register$', views.register, name='register'),
    url(r'^info$', views.info, name='info'),
    url(r'^edit_info$', views.edit_info, name='edit_info'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=20, unique=True, verbose_name='昵称')
    real_name = models.CharField(max_length=20, verbose_name='姓名')
    id_card = models.CharField(max_length=20, verbose_name='身份证号')
    city = models.CharField(max_length=20, verbose_name='城市')
    site = models.CharField(max_length=200, verbose_name='个人网站、博客')
    avatar = models.CharField(max_length=200, verbose_name='头像')

    def get_full_name(self):
        if self.nickname:
            return self.nickname
        else:
            return self.username

    def get_short_name(self):
        if self.nickname:
            return self.nickname
        else:
            return self.username

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import login as django_login_view
# from django.contrib.auth.models import UserManager
from .models import User


def login_view(request):
    """用户登录"""
    context = {}
    if request.method == 'POST':
        django_login_view(request)
        if not request.user.is_authenticated():
            context['error'] = 'error'

    return HttpResponseRedirect(reverse('blogs:index'))


def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    """注册"""
    if request.method == 'POST':
        data = request.POST
        password_ = data['password']
        nickname_ = data['nickname']

        new_user = User()
        new_user.username = data['username']
        new_user.email = data['email']
        new_user.set_password(password_)
        new_user.nickname = nickname_
        new_user.city = data['city']
        new_user.site = data['site']
        new_user.avatar = data['avatar']
        new_user.save()

        # user_manager = UserManager()
        # new_user = user_manager.create_user(username_, email_, password_, nickname=nickname_)

        authenticated_user = authenticate(username=nickname_, password=password_)
        login(request, authenticated_user)
        return HttpResponseRedirect(reverse('blogs:index'))

    return render(request, 'users/register.html')


def edit_info(request):
    """修改信息"""
    user = request.user
    if request.method == 'POST':
        data = request.POST
        # password_ = data['password']
        nickname_ = data['nickname']

        user.username = data['username']
        user.email = data['email']
        # user.set_password(password_)
        user.nickname = nickname_
        user.city = data['city']
        user.site = data['site']
        user.avatar = data['avatar']
        user.save()

        return HttpResponseRedirect(reverse('users:info'))
    else:
        context = {"user": user}
        return render(request, 'users/edit_info.html')


def info(request):
    """用户信息"""
    user = request.user

    context = {"user": user}
    return render(request, 'users/info.html', context)

users/templates/users/edit_info.html
{% extends "blogs/base.html" %}

{% block container %}

    <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-xs-10 col-sm-8 col-md-6">
        <form class="form-horizontal" method="post" action="{% url 'users:edit_info' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username" class="col-sm-3 col-sm-3 control-label">用户名 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="username" id="id_username" class="form-control" placeholder="用户名" maxlength="20" value="{{ user.username }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_nickname" class="col-sm-3 col-sm-3 control-label">昵称 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="nickname" id="id_nickname" class="form-control" placeholder="昵称" maxlength="20" value="{{ user.nickname }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="col-sm-3 control-label">邮箱 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="email" name="email" id="id_email" class="form-control" placeholder="邮箱" maxlength="30" value="{{ user.email }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_city" class="col-sm-3 control-label">城市 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="city" id="id_city" class="form-control" placeholder="城市" maxlength="30" value="{{ user.city }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_site" class="col-sm-3 control-label">个人网站、博客</label>
                <div class="col-sm-9">
                    <input type="text" name="site" id="id_site" class="form-control" placeholder="个人网站、博客" maxlength="200" value="{{ user.site }}">
                </div>
            </div>
            <div class="form-group">
                <label for="id_avatar" class="col-sm-3 control-label">头像 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="avatar" id="id_avatar" class="form-control" placeholder="头像" maxlength="200" value="{{ user.avatar }}" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_real_name" class="col-sm-3 control-label">姓名</label>
                <div class="col-sm-9">
                    <input type="text" name="real_name" id="id_real_name" class="form-control" placeholder="姓名" maxlength="30" value="{{ user.real_name }}">
                </div>
            </div>
            <div class="form-group">
                <label for="id_id_card" class="col-sm-3 control-label">身份证号</label>
                <div class="col-sm-9">
                    <input type="text" name="id_card" id="id_id_card" class="form-control" placeholder="身份证号" maxlength="18" value="{{ user.id_card }}">
                </div>
            </div>
{#            <div class="form-group">#}
{#                <label for="id_password" class="col-sm-3 control-label">密码 <span class="required">*</span></label>#}
{#                <div class="col-sm-9">#}
{#                    <input type="password" name="password" id="id_password" class="form-control" placeholder="密码" maxlength="30" required>#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <label for="id_password1" class="col-sm-3 control-label">确认密码 <span class="required">*</span></label>#}
{#                <div class="col-sm-9">#}
{#                    <input type="password" name="password1" id="id_password1" class="form-control" placeholder="请再次输入密码" maxlength="30" required>#}
{#                </div>#}
{#            </div>#}
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-4">
                    <button type="submit" class="btn btn-default">保存</button>
                </div>
            </div>
        </form>
    </div>

{% endblock container %}

users/templates/users/info.html
{% extends 'blogs/base.html' %}


{% block container %}
    <div align="right">
        <a href="{% url 'users:edit_info' %}" class="btn btn-default" role="button">编辑</a>
    </div>
    <div class="col-sm-offset-2 col-md-offset-4 col-xs-12 col-sm-8 col-md-4">
        <div align="center">
            <p><img src="{{ user.avatar }}" alt="{{ user.nickname }}" class="avatar" height="80" width="80"></p>
            <p>{{ user.nickname }}</p>
        </div>
        <p><hr></p>
        <div>
            <dl class="dl-horizontal">
                <dt>昵称</dt><dd>{{ user.username }}</dd>
                <dt>姓名</dt><dd>{{ user.real_name }}</dd>
                <dt>身份证号</dt><dd>{{ user.id_card }}</dd>
                <dt>邮箱</dt><dd><a href="mailto://{{ user.email }}">{{ user.email }}</a></dd>
                <dt>城市</dt><dd>{{ user.city }}</dd>
                <dt>个人网站、博客</dt><dd><a href="{{ user.site }}">{{ user.site }}</a></dd>
            </dl>
            <p><hr></p>
            <dl class="dl-horizontal">
                <dt>注册时长</dt><dd>{{ user.date_joined|timesince }}</dd>
                <dt>最后登录</dt><dd>{{ user.last_login|date:'Y年m月d日 H:i' }}</dd>
            </dl>
        </div>
    </div>

{% endblock container %}

users/templates/users/register.html
{% extends "blogs/base.html" %}

{% block container %}

    <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-xs-10 col-sm-8 col-md-6">
        <form class="form-horizontal" method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username" class="col-sm-3 col-sm-3 control-label">用户名 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="username" id="id_username" class="form-control" placeholder="用户名" maxlength="20" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_nickname" class="col-sm-3 col-sm-3 control-label">昵称 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="nickname" id="id_nickname" class="form-control" placeholder="昵称" maxlength="20" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_email" class="col-sm-3 control-label">邮箱 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="email" name="email" id="id_email" class="form-control" placeholder="邮箱" maxlength="30" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_city" class="col-sm-3 control-label">城市 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="city" id="id_city" class="form-control" placeholder="城市" maxlength="30" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_site" class="col-sm-3 control-label">个人网站、博客</label>
                <div class="col-sm-9">
                    <input type="text" name="site" id="id_site" class="form-control" placeholder="个人网站、博客" maxlength="30">
                </div>
            </div>
            <div class="form-group">
                <label for="id_avatar" class="col-sm-3 control-label">头像 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="text" name="avatar" id="id_avatar" class="form-control" placeholder="头像" maxlength="30" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_real_name" class="col-sm-3 control-label">姓名</label>
                <div class="col-sm-9">
                    <input type="text" name="real_name" id="id_real_name" class="form-control" placeholder="姓名" maxlength="30">
                </div>
            </div>
            <div class="form-group">
                <label for="id_id_card" class="col-sm-3 control-label">身份证号</label>
                <div class="col-sm-9">
                    <input type="text" name="id_card" id="id_id_card" class="form-control" placeholder="身份证号" maxlength="18">
                </div>
            </div>
            <div class="form-group">
                <label for="id_password" class="col-sm-3 control-label">密码 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="password" name="password" id="id_password" class="form-control" placeholder="密码" maxlength="30" required>
                </div>
            </div>
            <div class="form-group">
                <label for="id_password1" class="col-sm-3 control-label">确认密码 <span class="required">*</span></label>
                <div class="col-sm-9">
                    <input type="password" name="password1" id="id_password1" class="form-control" placeholder="请再次输入密码" maxlength="30" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-4">
                    <button type="submit" class="btn btn-default">注册</button>
                </div>
                <div class="col-sm-5">
                    <a href="{% url 'users:login_view' %}" class="btn btn-default">登录</a>
                </div>
            </div>
        </form>
    </div>

{% endblock container %}